-- 好漢草 Google Ads 工具 D1 schema（SQLite）。npx wrangler d1 execute heroherb-ads --file=schema.sql
create table if not exists settings (key text primary key, value text, grp text, role text, updated_at text);
create table if not exists sales_daily (day text, channel text, category text, revenue real, qty integer, orders integer, primary key (day, channel, category));
create table if not exists sales_monthly_costs (month text, label text, amount real, primary key (month, label));
create table if not exists ads_daily (day text, campaign_id text, campaign text, status text, cost real, impressions integer, clicks integer, conversions real, conv_value real, search_impr_share real, lost_is_budget real, primary key (day, campaign_id));
create table if not exists search_terms (day text, campaign_id text, term text, match text, cost real, clicks integer, conversions real, primary key (day, campaign_id, term));
create table if not exists ad_assets (asset_id text primary key, ad_id text, field text, text text, label text, impressions integer, updated_at text);
create table if not exists gsc_daily (day text, query text, page text, clicks integer, impressions integer, ctr real, position real, primary key (day, query, page));
create table if not exists ga4_daily (day text, source text, medium text, campaign text, sessions integer, users integer, purchases integer, revenue real, add_to_cart integer, primary key (day, source, medium, campaign));
create table if not exists trends_weekly (week text, keyword text, interest integer, source text, primary key (week, keyword));
create table if not exists keyword_ideas (run_id text, keyword text, avg_monthly integer, trend_12m text, competition text, bid_low real, bid_high real, judgement text, reason text, created_at text, primary key (run_id, keyword));
create table if not exists keyword_pool (keyword text primary key, status text, match text, source text, score real, ga4_sessions integer, gsc_position real, trends_interest integer, planner_volume integer, last_judged text, updated_at text);
create table if not exists keyword_map (keyword text primary key, cluster text, intent text, target_page text, note text);
create table if not exists seo_plan (id integer primary key autoincrement, week text, type text, title text, keywords text, event_id text, target_page text, status text, created_at text);
create table if not exists calendar_overrides (name text, year integer, start text, end text, primary key (name, year));
create table if not exists title_library (text text primary key, field text, label text, impressions integer, wins integer, losses integer, updated_at text);
create table if not exists briefs (id integer primary key autoincrement, event_id text, title text, status text, current_version integer, created_at text, approved_at text, approved_by text);
create table if not exists brief_versions (brief_id integer, version integer, draft text, flags text, feedback text, created_at text, primary key (brief_id, version));
create table if not exists launch_plans (id integer primary key autoincrement, brief_id integer, plan text, validate_result text, applied text, status text, created_at text, applied_at text);
create table if not exists actions (id integer primary key autoincrement, kind text, target text, payload text, actor text, created_at text);
create table if not exists budget_log (id integer primary key autoincrement, day text, campaign_id text, before_amount real, after_amount real, reason text, mode text, applied integer, created_at text);
create table if not exists weather_daily (day text, region text, min_temp real, max_temp real, pop integer, primary key (day, region));
create table if not exists alerts (id integer primary key autoincrement, day text, level text, kind text, title text, body text, handled integer default 0, created_at text);
create table if not exists suggestions (id integer primary key autoincrement, week text, kind text, body text, status text, created_at text);
create table if not exists experiment_log (id integer primary key autoincrement, name text, started text, ended text, result text);
create table if not exists sync_log (id integer primary key autoincrement, job text, ok integer, rows integer, message text, created_at text);
create index if not exists idx_ads_daily_day on ads_daily(day);
create index if not exists idx_gsc_day on gsc_daily(day);
create index if not exists idx_ga4_day on ga4_daily(day);
